# Site settings
title: Baby Motions - うつぶせ寝を検知し、赤ちゃんのもしもに備える
description: >- # this means to ignore newlines until "baseurl:"
  Baby Motionsは、AIがスマホカメラで赤ちゃんのうつぶせ寝を検知し、
  SIDS(乳幼児突然死症候群)のリスクに備えるWebアプリです。

# Correct settings for a GitHub Project Page
# https://<username>.github.io/<repository-name>
url: "https://baby-feelings.github.io" # リポジトリ名を含まないドメイン部分
baseurl: "/baby_motions.github.io"   # リポジトリ名をスラッシュから始める

github_username: baby-feelings

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/