# Site settings
title: Baby Motions - うつぶせ寝を検知し、赤ちゃんのもしもに備える
description: >- # this means to ignore newlines until "baseurl:"
  Baby Motionsは、AIがスマホカメラで赤ちゃんのうつぶせ寝を検知し、
  SIDS(乳幼児突然死症候群)のリスクに備えるWebアプリです。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://baby_motions.github.io" # your-github-username.github.io
github_username: baby-feelings

# Build settings
theme: null
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/